import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { SiteHeader } from "@/components/site-header";

export const metadata: Metadata = { title: "TAG Global Conference 2027", description: "A global gathering for ambitious young leaders, mentors, and families." };

const themes = [
  ["01", "Navigating Purpose & Identity", "Build a grounded sense of identity and learn to make values-led decisions with clarity."],
  ["02", "Career Conversations & Industry Roundtables", "Speak directly with professionals shaping technology, medicine, finance, policy, and culture."],
  ["03", "Faith & Purpose Dialogues", "Explore how conviction, calling, and service can anchor ambition and global impact."],
  ["04", "Practical Workshops & Labs", "Turn ideas into action through guided challenges, skills practice, and collaborative problem-solving."],
  ["05", "Global Community Connection", "Meet peers from different cities and nations who share the courage to build meaningful futures."],
];

const speakers = [
  ["Dr. Eliana Boateng", "Education & Youth Development", "old", "0%"],
  ["Marcus Chen", "Finance & Responsible Enterprise", "old", "33.333%"],
  ["Dr. Sarah Jenkins", "Medicine & Human Potential", "old", "66.666%"],
  ["David Osei", "Creative Leadership", "old", "100%"],
  ["Samuel Adebayo", "Law, Policy & Justice", "new", "50%"],
  ["Amina Al-Mansoor", "Engineering & Innovation", "new", "100%"],
];

const agenda = [
  ["09:00", "Opening Ceremony", "Welcome, worship, and the global youth leadership keynote.", "Main Stage"],
  ["10:30", "Future Skills Labs", "Parallel hands-on workshops across technology, enterprise, and communication.", "Learning Hubs"],
  ["12:30", "Community Lunch", "Curated peer tables connecting young people with mentors and partners.", "Forum Hall"],
  ["14:00", "Industry Roundtables", "Candid conversations with leaders from medicine, policy, finance, and media.", "Breakout Rooms"],
  ["16:00", "Purpose in Practice", "Personal action planning, coaching circles, and next-step commitments.", "Main Stage"],
  ["17:30", "Commissioning", "Celebration, awards, and the launch of the 2027 youth action network.", "Main Stage"],
];

export default function ConferencesPage() { return <main className="bg-white text-secondary"><SiteHeader active="conferences" />
  <section className="px-5 py-16 lg:px-8 lg:py-20"><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[1.05fr_.95fr]"><div><p className="inline-flex rounded-full bg-blue-100 px-3 py-1.5 text-[.65rem] font-black uppercase tracking-[.14em] text-primary">Flagship global gathering · 2027</p><h1 className="mt-7 text-5xl font-black leading-[.98] sm:text-6xl">TAG GLOBAL<br/>CONFERENCE 2027</h1><p className="mt-4 text-xl font-bold text-primary">Becoming: Purpose, Possibility & Global Impact</p><p className="mt-6 max-w-2xl text-sm leading-7 text-slate-600">A transformative one-day gathering equipping young people to discover their voice, expand their possibilities, and build the confidence to lead with faith and purpose.</p><div className="mt-7 flex flex-wrap gap-4 text-xs font-bold text-slate-600"><span>17 July 2027</span><span>London + Global Virtual Hubs</span><span>Ages 14–24</span></div><div className="mt-8 flex flex-wrap gap-3"><button className="rounded-md bg-tertiary px-5 py-3.5 text-sm font-black text-slate-950">Register for Conference →</button><button className="rounded-md border border-slate-300 px-5 py-3.5 text-sm font-black text-primary">Download Event Guide</button></div></div><div className="relative aspect-[16/11] overflow-hidden rounded-lg shadow-[0_24px_60px_rgba(15,23,42,.18)]"><Image alt="Young leader speaking at the TAG global conference" className="object-cover" fill priority sizes="(max-width:1024px) 100vw, 48vw" src="/images/tag-conference-stage.png"/><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-slate-950/85 to-transparent p-6 text-white"><p className="text-xs font-black uppercase tracking-[.14em] text-blue-200">Live from the global stage</p><p className="mt-2 text-lg font-black">A room built for possibility</p></div></div></div></section>

  <section className="border-y border-slate-200 bg-slate-50 px-5 py-8 lg:px-8"><div className="mx-auto grid max-w-7xl gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["1,000+", "Young people"], ["25+", "World-class speakers"], ["12+", "Countries connected"], ["1", "Transformative day"]].map(([value,label],index)=><div className="flex items-center gap-4 rounded-md bg-white p-5" key={label}><span className={`grid size-10 place-items-center rounded-md text-xs font-black ${index===2?"bg-amber-100 text-amber-700":"bg-blue-100 text-primary"}`}>{index+1}</span><div><p className="text-2xl font-black">{value}</p><p className="text-xs text-slate-500">{label}</p></div></div>)}</div></section>

  <section className="px-5 py-20 lg:px-8 lg:py-24"><div className="mx-auto max-w-7xl"><p className="eyebrow text-left">Why this gathering matters</p><h2 className="section-title max-w-2xl text-left">One Day. New Perspectives. Bigger Possibilities.</h2><p className="mt-5 max-w-3xl text-sm leading-7 text-slate-500">The conference creates a high-trust environment where young people can ask honest questions, encounter new pathways, and leave with practical tools and relationships.</p><div className="mt-11 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{themes.map(([number,title,copy],index)=><article className={`rounded-md p-6 ${index===4?"border border-blue-100 bg-blue-50 lg:col-span-2":"bg-slate-50"}`} key={title}><span className={`grid size-9 place-items-center rounded-md text-xs font-black ${index===2?"bg-amber-100 text-amber-700":"bg-blue-100 text-primary"}`}>{number}</span><h3 className="mt-5 text-base font-black">{title}</h3><p className="mt-3 text-xs leading-6 text-slate-500">{copy}</p></article>)}</div></div></section>

  <section className="bg-slate-50 px-5 py-20 lg:px-8 lg:py-24"><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[1fr_.8fr]"><div><p className="eyebrow text-left">The conference theme</p><h2 className="section-title text-left">Becoming.</h2><p className="mt-5 text-xl font-semibold">Purpose. Potential. Possibility.</p><div className="mt-5 space-y-4 text-sm leading-7 text-slate-500"><p>Becoming is not a destination. It is the daily courage to grow into the person God designed you to be, even before every answer is clear.</p><p>This year&apos;s conference invites young people to move beyond inherited limits, develop a global outlook, and practise leadership that serves others.</p></div><div className="mt-8 grid gap-3 sm:grid-cols-3">{[["Purpose", "Know what anchors you"], ["Possibility", "See beyond circumstance"], ["Practice", "Take the next faithful step"]].map(([t,c])=><div className="rounded-md bg-white p-4" key={t}><p className="text-xs font-black text-primary">{t}</p><p className="mt-2 text-[.65rem] leading-5 text-slate-500">{c}</p></div>)}</div></div><blockquote className="rounded-lg bg-white p-8 shadow-[0_12px_40px_rgba(15,23,42,.06)]"><span className="text-5xl font-serif text-blue-200">“</span><p className="mt-3 text-xl font-black leading-8">You don&apos;t need to have everything figured out. You need courage, community, and the willingness to keep becoming.</p><footer className="mt-6 text-xs font-bold text-primary">TAG Global Conference Team</footer></blockquote></div></section>

  <section className="px-5 py-20 lg:px-8 lg:py-24"><div className="mx-auto max-w-7xl"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow text-left">Meet the faculty</p><h2 className="section-title text-left">Meet This Year&apos;s Speakers</h2><p className="section-copy mx-0 text-left">Leaders bringing expertise, wisdom, and a genuine commitment to the next generation.</p></div><Link className="text-sm font-black text-primary" href="/mentors">Explore our mentor network →</Link></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{speakers.map(([name,role,asset,position])=><article className="overflow-hidden rounded-md border border-slate-200" key={name}><div className={`h-72 bg-no-repeat ${asset==="old"?"bg-[url('/images/tag-mentors.png')] bg-[length:400%_100%]":"bg-[url('/images/tag-mentor-directory.png')] bg-[length:300%_100%]"}`} style={{backgroundPosition:`${position} center`}}/><div className="p-5"><h3 className="font-black">{name}</h3><p className="mt-1 text-xs text-slate-500">{role}</p><p className="mt-4 text-[.65rem] font-bold text-primary">View session →</p></div></article>)}</div></div></section>

  <section className="bg-slate-50 px-5 py-20 lg:px-8"><div className="mx-auto max-w-7xl"><p className="eyebrow text-left">Conference programme</p><h2 className="section-title text-left">What&apos;s Happening</h2><p className="section-copy mx-0 text-left">A focused day moving from inspiration to practical action.</p><div className="mt-10 space-y-3">{agenda.map(([time,title,copy,venue],index)=><article className="grid gap-4 rounded-md border border-slate-200 bg-white p-5 sm:grid-cols-[90px_1fr_auto] sm:items-center" key={title}><span className={`w-fit rounded-md px-3 py-2 text-xs font-black ${index===2||index===5?"bg-amber-100 text-amber-700":"bg-blue-100 text-primary"}`}>{time}</span><div><h3 className="text-sm font-black">{title}</h3><p className="mt-1 text-xs text-slate-500">{copy}</p></div><span className="text-[.65rem] font-bold text-slate-400">{venue}</span></article>)}</div></div></section>

  <section className="px-5 py-20 lg:px-8 lg:py-24"><div className="mx-auto max-w-7xl"><p className="eyebrow">A seat for every future</p><h2 className="section-title">Who Should Attend</h2><p className="section-copy">Young people, the adults who guide them, and the institutions building pathways forward.</p><div className="mt-10 grid gap-5 lg:grid-cols-3">{[["Teenagers & Young Adults", "Discover direction, meet mentors, and find peers who take your dreams seriously.", "0%"], ["Parents & Guardians", "Gain practical insight into supporting purpose, wellbeing, education, and career choices.", "50%"], ["Mentors, Educators & Youth Leaders", "Exchange proven approaches and connect with a global community of practice.", "100%"]].map(([title,copy,position])=><article className="overflow-hidden rounded-md border border-slate-200" key={title}><div className="h-48 bg-[url('/images/tag-training-library.png')] bg-[length:300%_100%] bg-no-repeat" style={{backgroundPosition:`${position} center`}}/><div className="p-6"><h3 className="text-lg font-black">{title}</h3><p className="mt-3 text-xs leading-6 text-slate-500">{copy}</p><p className="mt-5 text-xs font-black text-primary">Learn more →</p></div></article>)}</div></div></section>

  <section className="bg-white px-5 py-20 lg:px-8 lg:py-24"><div className="mx-auto max-w-7xl"><p className="eyebrow">The authentic experience</p><h2 className="section-title">More Than a Conference</h2><p className="section-copy">A place to learn, connect, ask questions, discover opportunities and imagine what&apos;s possible.</p><div className="mt-10 grid gap-3 md:grid-cols-6">
    <div className="relative min-h-80 overflow-hidden rounded-lg md:col-span-4 md:min-h-[430px]"><Image alt="A packed TAG global conference auditorium" className="object-cover" fill sizes="(max-width:768px) 100vw, 66vw" src="/images/tag-conference-stage.png"/><div className="absolute inset-0 bg-gradient-to-t from-slate-950/85 via-transparent to-transparent"/><div className="absolute inset-x-0 bottom-0 p-5 text-white"><p className="text-[.58rem] font-black uppercase tracking-[.14em] text-amber-300">Passionate assemblies</p><p className="mt-1 text-sm font-black sm:text-base">Over 1,400 youth unified in pursuit of godly excellence</p></div></div>
    <div className="relative min-h-72 overflow-hidden rounded-lg md:col-span-2 md:min-h-[430px]"><Image alt="Young people discussing ideas with a mentor" className="object-cover" fill sizes="(max-width:768px) 100vw, 33vw" src="/images/tag-about-community.png"/><div className="absolute inset-0 bg-gradient-to-t from-slate-950/85 via-transparent to-transparent"/><div className="absolute inset-x-0 bottom-0 p-5 text-white"><p className="text-[.58rem] font-black uppercase tracking-[.14em] text-amber-300">Close mentorship</p><p className="mt-1 text-sm font-black">Real questions answered with honesty</p></div></div>
    {["0%", "50%", "100%"].map((position,index)=><div className="relative min-h-64 overflow-hidden rounded-lg md:col-span-2" key={position}><div className="absolute inset-0 bg-[url('/images/tag-training-library.png')] bg-[length:300%_100%] bg-no-repeat" style={{backgroundPosition:`${position} center`}}/><div className="absolute inset-0 bg-gradient-to-t from-slate-950/90 via-transparent to-transparent"/><div className="absolute inset-x-0 bottom-0 p-5 text-white"><p className="text-[.58rem] font-black uppercase tracking-[.14em] text-amber-300">{["Practical labs", "Spiritual encounter", "Commissioning"][index]}</p><p className="mt-1 text-sm font-black">{["Building technology and ventures", "Unapologetic faith in reflection", "Celebration of future leaders"][index]}</p></div></div>)}
  </div></div></section>

  <section className="bg-slate-50 px-5 py-16 lg:px-8 lg:py-20"><div className="mx-auto max-w-7xl rounded-lg bg-primary px-7 py-12 text-white shadow-[0_20px_55px_rgba(37,99,235,.2)] sm:px-12 lg:px-16"><p className="inline-flex rounded-full bg-white/10 px-3 py-1.5 text-[.6rem] font-black uppercase tracking-[.14em] text-blue-100">Secure your place · London hub & online</p><h2 className="mt-5 max-w-3xl text-3xl font-black leading-tight sm:text-5xl">Your Next Chapter Could Start Here.</h2><p className="mt-4 max-w-3xl text-sm leading-7 text-blue-100">Join 1,500+ teenagers, young adults, mentors and global professionals for TAG Global Conference 2027. Early bird passes expire June 30. Subsidised bursaries are available for school cohorts.</p><form className="mt-8 flex max-w-3xl flex-col gap-3 sm:flex-row"><label className="sr-only" htmlFor="conference-email">Attendee or parent email address</label><input className="h-12 flex-1 rounded-md bg-white px-4 text-sm text-secondary outline-none ring-white/30 focus:ring-4" id="conference-email" placeholder="Enter attendee or parent email address" required type="email"/><button className="h-12 rounded-md bg-tertiary px-6 text-sm font-black text-slate-950" type="submit">Register for TAG 2027</button></form><div className="mt-7 flex flex-wrap gap-x-6 gap-y-3 text-[.62rem] font-bold text-blue-100"><a className="underline" href="#">Download Conference Pack (PDF)</a><a className="underline" href="/contact">Ask a Question / School Bookings</a><span>Full travel & safeguarding document</span></div></div></section>

  <section className="bg-slate-50 px-5 py-20 lg:px-8 lg:py-24"><div className="mx-auto max-w-7xl"><p className="eyebrow text-left">The archives & legacy</p><h2 className="section-title text-left">Previous Conferences</h2><p className="section-copy mx-0 text-left">Explore previous TAG conferences, meet past speakers, and revisit conversations that have helped young people grow in purpose, knowledge, and confidence.</p><div className="mt-10 grid gap-5 lg:grid-cols-3">
    {[{year:"2026",theme:"Built for More",copy:"A generation discovering courageous purpose, leadership, and practical pathways for meaningful influence.",image:"stage"},{year:"2025",theme:"Beyond Limits",copy:"Conversations on confidence, global exposure, faith, and the courage to build beyond inherited limitations.",image:"community"},{year:"2024",theme:"Identity & Impact",copy:"The foundation conference that launched the TAG international mentor network and youth development vision.",image:"training"}].map((event)=><article className="overflow-hidden rounded-lg border border-slate-200 bg-white" key={event.year}><div className="relative aspect-[16/9] overflow-hidden">{event.image==="stage"?<Image alt={`TAG Global Conference ${event.year}`} className="object-cover" fill sizes="(max-width:1024px) 100vw, 33vw" src="/images/tag-conference-stage.png"/>:event.image==="community"?<Image alt={`TAG Global Youth Summit ${event.year}`} className="object-cover" fill sizes="(max-width:1024px) 100vw, 33vw" src="/images/tag-about-community.png"/>:<div className="absolute inset-0 bg-[url('/images/tag-training-library.png')] bg-[length:300%_100%] bg-center bg-no-repeat"/>}<span className="absolute bottom-3 right-3 rounded bg-primary px-2 py-1 text-[.58rem] font-black text-white">{event.year} Highlights</span></div><div className="p-6"><h3 className="text-lg font-black">TAG Global Conference {event.year}</h3><p className="mt-2 text-xs font-black text-primary">“{event.theme}”</p><p className="mt-4 text-xs leading-6 text-slate-500">{event.copy}</p><button className="mt-6 h-10 w-full rounded-md bg-slate-100 text-xs font-black text-primary">Explore {event.year} Archive →</button></div></article>)}
  </div>
  <div className="mt-16"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="eyebrow text-left">Video vault</p><h2 className="mt-2 text-2xl font-black">Featured Recorded Sessions & Replays</h2></div><div className="flex flex-wrap gap-2">{["All", "Leadership", "Career", "Faith & Purpose", "Technology"].map((item,index)=><button className={`rounded-full px-3 py-2 text-[.62rem] font-bold ${index===0?"bg-primary text-white":"bg-white text-slate-600"}`} key={item}>{item}</button>)}</div></div><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Opening Keynote: Defining Who You Were Created to Be","Dr. Eliana Boateng","stage",""],["Financial Literacy & Kingdom Investing for Gen-Z","Marcus Chen","training","100%"],["Raising Leaders in an Anxious World: Youth & Family","Dr. Sarah Jenkins","community",""],["Turning Personal Pain into Purpose-Driven Ventures","David Osei","training","50%"]].map(([title,speaker,asset,position])=><article className="overflow-hidden rounded-md border border-slate-200 bg-white" key={title}><div className="relative aspect-video overflow-hidden">{asset==="stage"?<Image alt={title} className="object-cover" fill sizes="(max-width:1024px) 50vw, 25vw" src="/images/tag-conference-stage.png"/>:asset==="community"?<Image alt={title} className="object-cover" fill sizes="(max-width:1024px) 50vw, 25vw" src="/images/tag-about-community.png"/>:<div className="absolute inset-0 bg-[url('/images/tag-training-library.png')] bg-[length:300%_100%] bg-no-repeat" style={{backgroundPosition:`${position} center`}}/>}<span className="absolute left-1/2 top-1/2 grid size-11 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full bg-white text-primary shadow-lg">▶</span></div><div className="p-5"><h3 className="text-sm font-black leading-5">{title}</h3><p className="mt-3 text-[.65rem] text-slate-500">With {speaker}</p><button className="mt-5 text-[.65rem] font-black text-primary">Watch Session →</button></div></article>)}</div></div>
  </div></section>

  <section className="bg-white px-5 py-20 lg:px-8 lg:py-24"><div className="mx-auto max-w-7xl"><p className="eyebrow">Voices of transformation</p><h2 className="section-title">What People Took Away</h2><p className="section-copy">Hear directly from delegates, parents, and keynote mentors who joined our previous summits.</p><div className="mt-10 grid gap-5 lg:grid-cols-3">{[["Teen delegate","For the first time, I wasn’t told to wait until I grow up. TAG treated my calling with seriousness and gave me a mentor who believes in me.","Kelechi O."],["Parent forum","The safeguarding, spiritual depth, and calibre of professionals blew us away. My son came home with clear direction and renewed focus.","Mrs. Adeyemi"],["Keynote mentor","These young minds are sharper and hungrier than most corporate boardrooms. Mentoring at TAG is the highlight of my year.","Dr. Eliana Boateng"]].map(([label,quote,name],index)=><blockquote className={`rounded-lg border p-7 ${index===2?"border-amber-100 bg-amber-50":"border-slate-200 bg-slate-50"}`} key={name}><div className="flex items-start justify-between"><p className={`text-[.6rem] font-black uppercase tracking-[.12em] ${index===2?"text-amber-700":"text-primary"}`}>{label}</p><span className="text-5xl font-black text-slate-200">”</span></div><p className="mt-3 text-sm font-semibold leading-7">“{quote}”</p><footer className="mt-6 text-xs font-black">{name}<span className="block font-normal text-slate-500">TAG Conference Community</span></footer></blockquote>)}</div></div></section>

  <footer className="border-t border-slate-200 bg-white px-5 py-12 lg:px-8"><div className="mx-auto grid max-w-7xl gap-10 sm:grid-cols-2 lg:grid-cols-4"><div><Link className="text-xl font-black text-primary" href="/">TAG</Link><p className="mt-4 max-w-xs text-xs leading-6 text-slate-500">© 2026 Teens Academy Global.<br/>Potential should never be limited by circumstance.</p></div><div><p className="footer-title">Explore</p><Link href="/about">About</Link><Link href="/mentors">Mentors</Link><Link href="/training">Training</Link></div><div><p className="footer-title">Connect</p><Link href="/conferences">Conferences</Link><Link href="/contact">Contact</Link><Link href="#">Partnerships</Link></div><div><p className="footer-title">Legal</p><Link href="#">Privacy Policy</Link><Link href="#">Terms of Service</Link><Link href="#">Safeguarding</Link></div></div></footer>
</main>; }
