import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { SiteHeader } from "@/components/site-header";

export const metadata: Metadata = { title: "Training | Teens Academy Global", description: "Masterclasses, workshops, and practical training for young people." };

const resources = [
  ["Technology", "Introduction to Future Tech & AI Ethics", "Understanding the moral implications of building tomorrow's technology today.", "12:45", "0%"],
  ["Leadership", "Finding Your Voice in Crowded Rooms", "Practical strategies for establishing presence, authority, and authentic influence.", "45:20", "50%"],
  ["Career", "Resume Structuring for Impact", "A rapid guide to formatting your experience to catch a recruiter's eye.", "08:15", "100%"],
];

export default function TrainingPage() { return <main className="bg-white text-secondary"><SiteHeader active="training" />
  <section className="bg-slate-50 px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><h1 className="max-w-3xl text-5xl font-black leading-[1.05] sm:text-6xl">Knowledge That Helps Young People Move Forward</h1><p className="mt-6 max-w-2xl text-base leading-8 text-slate-600">Access our curated library of masterclasses, skill-building workshops, and industry insights designed to accelerate your personal and professional growth.</p><div className="mt-12 flex flex-wrap gap-3">{["All Resources", "Career Pathways", "Technology & Tech", "Leadership", "Mental Wellbeing"].map((item,index)=><button className={`rounded-full px-5 py-2.5 text-xs font-bold ${index===0?"bg-primary text-white":"bg-slate-200 text-slate-700"}`} key={item}>{item}</button>)}</div>
    <div className="mt-10 grid gap-5 lg:grid-cols-3">{resources.map(([category,title,copy,duration,position])=><article className="overflow-hidden rounded-lg border border-slate-200 bg-white" key={title}><div className="relative aspect-[16/9] bg-[url('/images/tag-training-library.png')] bg-[length:300%_100%] bg-no-repeat" style={{backgroundPosition:`${position} center`}}><span className="absolute left-1/2 top-1/2 grid size-14 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full bg-white text-xl text-primary shadow-lg">▶</span><span className="absolute bottom-3 right-3 rounded bg-slate-950/80 px-2 py-1 text-[.62rem] font-bold text-white">{duration}</span></div><div className="p-6"><p className="text-[.62rem] font-black uppercase tracking-[.12em] text-primary">{category} · Masterclass</p><h2 className="mt-4 text-xl font-black leading-tight">{title}</h2><p className="mt-3 text-sm leading-6 text-slate-500">{copy}</p></div></article>)}</div><div className="mt-9 text-center"><button className="text-sm font-black text-primary">Explore Full Library →</button></div></div></section>

  <section className="px-5 py-20 lg:px-8 lg:py-24"><div className="mx-auto max-w-7xl"><div className="flex flex-col gap-6 md:flex-row md:items-start md:justify-between"><div><h2 className="text-3xl font-black sm:text-4xl">Real Stories. Real Growth.</h2><p className="mt-4 max-w-2xl text-base leading-7 text-slate-500">Hear directly from the young people accelerating their potential, and the parents supporting their journey.</p></div><div className="inline-flex self-start rounded-full bg-slate-100 p-1 text-xs font-bold"><button className="rounded-full bg-primary px-5 py-2 text-white">Young People</button><button className="px-5 py-2 text-slate-600">Parents & Guardians</button></div></div>
    <div className="mt-12 grid gap-5 lg:grid-cols-3"><blockquote className="rounded-lg bg-slate-50 p-8"><span className="text-5xl font-black text-slate-200">”</span><p className="mt-5 text-xl font-semibold leading-8">Before joining the academy, I wasn&apos;t sure how to translate my interest in coding into an actual career path. The mentorship here completely shifted my perspective.</p><footer className="mt-8 flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full bg-primary text-xs font-black text-white">MJ</span><span className="text-xs font-black">Marcus Johnson<small className="block font-normal text-slate-500">Alumni, Tech Innovators Program</small></span></footer></blockquote>
      <figure className="overflow-hidden rounded-lg bg-slate-50"><div className="relative aspect-[4/5]"><Image alt="TAG learner Sarah Chen" className="object-cover" fill sizes="(max-width:1024px) 100vw, 33vw" src="/images/tag-training-student.png" /></div><figcaption className="p-7"><p className="text-base italic leading-7">“The network you build here is incredible. I&apos;m still in touch with my mentor weekly, and the confidence I&apos;ve gained is immeasurable.”</p><p className="mt-5 text-xs font-black">Sarah Chen <span className="block font-normal text-slate-500">Current Student</span></p></figcaption></figure>
      <div className="grid gap-5"><blockquote className="rounded-lg bg-primary p-8 text-white"><span className="text-5xl font-black text-blue-300">”</span><p className="mt-4 text-xl font-semibold leading-8">A truly transformative environment that demands excellence while providing unwavering support. It&apos;s rare to find this balance.</p><footer className="mt-7 text-xs font-black">David Okafor <span className="block font-normal text-blue-200">Leadership Cohort &apos;23</span></footer></blockquote><blockquote className="rounded-lg bg-slate-50 p-8"><p className="text-sm leading-7 text-slate-600">“I applied for the enterprise program just to see what would happen. Nine months later, I&apos;ve successfully pitched my startup idea to a room full of real investors.”</p><footer className="mt-7 border-t border-slate-200 pt-5 text-xs font-black">Emma Lewis <span className="block font-normal text-slate-500">Young Entrepreneur Award Winner</span></footer></blockquote></div>
    </div></div></section>

  <footer id="contact" className="border-t border-slate-100 bg-white px-5 py-12 lg:px-8"><div className="mx-auto grid max-w-7xl gap-10 sm:grid-cols-2 lg:grid-cols-4"><div><Link className="text-xl font-black text-primary" href="/">TAG</Link><p className="mt-5 max-w-xs text-sm leading-6 text-slate-500">Potential should never be limited by circumstance.</p></div><div><p className="footer-title">Explore</p><Link href="/">Home</Link><Link href="/#programs">Programs</Link><Link href="/training">Training</Link><Link href="/mentors">Mentors</Link></div><div><p className="footer-title">Connect</p><Link href="/#summit">Conferences</Link><Link href="#">Testimonials</Link><Link href="#">Safeguarding</Link></div><div><p className="footer-title">Legal</p><Link href="#">Privacy Policy</Link><Link href="#">Terms of Service</Link></div></div><p className="mx-auto mt-12 max-w-7xl border-t border-slate-100 pt-7 text-center text-xs text-slate-500">© 2026 Teens Academy Global.</p></footer>
</main>; }
